# Generated by Django 5.1.3 on 2024-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacion', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
