# Generated by Django 5.1.3 on 2024-12-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacion', '0005_remove_item_item_colors_delete_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=6),
            preserve_default=False,
        ),
    ]
