# Generated by Django 5.1.3 on 2024-12-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacion', '0006_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
